const styles = {
  page: {
    minHeight: '100vh',
    background: '#f1f5f9',
  },

  navbar: {
    background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
    padding: '0 32px',
    height: '60px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    boxShadow: '0 2px 12px rgba(59,130,246,0.30)',
  },
  navLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  navLogoBox: {
    width: '36px',
    height: '36px',
    background: 'rgba(255,255,255,0.20)',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navTitle: {
    color: '#ffffff',
    fontSize: '17px',
    fontWeight: '700',
  },
  navRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  navUser: {
    color: 'rgba(255,255,255,0.90)',
    fontSize: '14px',
    fontWeight: '500',
  },
  btnLogout: {
    padding: '8px 18px',
    background: 'rgba(255,255,255,0.15)',
    color: '#ffffff',
    border: '1px solid rgba(255,255,255,0.30)',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'background 0.2s',
  },

  content: {
    padding: '36px 40px',
    maxWidth: '1100px',
    margin: '0 auto',
  },
  welcomeBox: {
    background: '#ffffff',
    borderRadius: '12px',
    padding: '28px 32px',
    marginBottom: '24px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  welcomeAvatar: {
    width: '52px',
    height: '52px',
    background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#ffffff',
    fontSize: '22px',
    fontWeight: '700',
    flexShrink: 0,
    overflow: 'hidden',
  },
  welcomeAvatarImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  welcomeTitle: {
    fontSize: '20px',
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: '2px',
  },
  welcomeSub: {
    fontSize: '14px',
    color: '#64748b',
  },

  sectionTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: '16px',
  },
  habitsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '16px',
    marginBottom: '28px',
  },
  habitCard: {
    background: '#ffffff',
    borderRadius: '12px',
    padding: '20px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
  },
  habitIcon: {
    fontSize: '28px',
    marginBottom: '10px',
  },
  habitName: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#0f172a',
    marginBottom: '4px',
  },
  habitMeta: {
    fontSize: '13px',
    color: '#64748b',
    marginBottom: '12px',
  },
  progressBar: {
    height: '6px',
    background: '#e2e8f0',
    borderRadius: '999px',
    overflow: 'hidden',
    marginBottom: '6px',
  },
  progressFill: {
    height: '100%',
    borderRadius: '999px',
    transition: 'width 0.4s',
  },
  progressText: {
    fontSize: '12px',
    color: '#64748b',
    textAlign: 'right',
  },
  habitHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: '18px',
    gap: '20px',
  },
  sectionSub: {
    fontSize: '14px',
    color: '#475569',
  },
  newHabitForm: {
    display: 'grid',
    gridTemplateColumns: '1.5fr 1.2fr 0.8fr',
    gap: '12px',
    alignItems: 'end',
    marginBottom: '20px',
    padding: '20px',
    borderRadius: '14px',
    background: '#ffffff',
    border: '1px solid #e2e8f0',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  formGroupSmall: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    minWidth: '100px',
  },
  formLabel: {
    fontSize: '13px',
    color: '#475569',
  },
  formInput: {
    width: '100%',
    minHeight: '42px',
    padding: '10px 14px',
    borderRadius: '10px',
    border: '1px solid #cbd5e1',
    fontSize: '14px',
    color: '#0f172a',
    outline: 'none',
    boxSizing: 'border-box',
  },
  btnPrimary: {
    padding: '12px 18px',
    background: '#2563eb',
    color: '#ffffff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '700',
    cursor: 'pointer',
  },
  btnSecondary: {
    padding: '10px 14px',
    background: '#e2e8f0',
    color: '#0f172a',
    border: 'none',
    borderRadius: '10px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  btnDanger: {
    padding: '10px 14px',
    background: '#ef4444',
    color: '#ffffff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '13px',
    fontWeight: '700',
    cursor: 'pointer',
  },
  errorBox: {
    margin: '0 0 18px',
    padding: '14px 16px',
    background: '#fee2e2',
    color: '#b91c1c',
    borderRadius: '12px',
    border: '1px solid #fecaca',
  },
  habitCardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '14px',
    marginBottom: '12px',
  },
  habitCardHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  habitMenu: {
    position: 'relative',
  },
  habitMenuButton: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    border: '1px solid #cbd5e1',
    background: '#ffffff',
    color: '#475569',
    fontSize: '18px',
    cursor: 'pointer',
    display: 'grid',
    placeItems: 'center',
  },
  habitMenuDropdown: {
    position: 'absolute',
    right: 0,
    top: '44px',
    width: '180px',
    padding: '8px',
    borderRadius: '14px',
    border: '1px solid #e2e8f0',
    background: '#ffffff',
    boxShadow: '0 12px 32px rgba(15,23,42,0.08)',
    zIndex: 10,
    display: 'grid',
    gap: '8px',
  },
  habitMenuItem: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '10px',
    border: 'none',
    background: '#f8fafc',
    color: '#0f172a',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '14px',
  },
  habitMenuItemDanger: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '10px',
    border: 'none',
    background: '#fee2e2',
    color: '#b91c1c',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '14px',
  },
  editHabitPanel: {
    padding: '16px',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    background: '#f8fafc',
    marginBottom: '16px',
  },
  editHabitRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
    marginBottom: '12px',
  },
  editHabitActions: {
    display: 'flex',
    gap: '10px',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  activitySection: {
    marginTop: '18px',
  },
  activityTitle: {
    fontSize: '14px',
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: '10px',
  },
  emptyText: {
    fontSize: '13px',
    color: '#64748b',
    marginBottom: '12px',
  },
  activityList: {
    margin: 0,
    padding: 0,
    listStyle: 'none',
    display: 'grid',
    gap: '10px',
    marginBottom: '12px',
  },
  activityItem: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '10px',
    fontSize: '14px',
    color: '#0f172a',
  },
  activityItemLeft: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
  },
  activityButton: {
    width: '30px',
    height: '30px',
    borderRadius: '8px',
    border: '1px solid #cbd5e1',
    background: '#ffffff',
    cursor: 'pointer',
    fontWeight: '700',
    color: '#334155',
    flexShrink: 0,
  },
  activityItemRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
  },
  activityMenu: {
    position: 'relative',
  },
  activityMenuButton: {
    width: '30px',
    height: '30px',
    borderRadius: '50%',
    border: '1px solid #cbd5e1',
    background: '#ffffff',
    color: '#64748b',
    fontSize: '18px',
    cursor: 'pointer',
    display: 'grid',
    placeItems: 'center',
  },
  activityMenuDropdown: {
    position: 'absolute',
    right: 0,
    top: '40px',
    width: '150px',
    padding: '8px',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    background: '#ffffff',
    boxShadow: '0 10px 24px rgba(15,23,42,0.08)',
    zIndex: 10,
    display: 'grid',
    gap: '8px',
  },
  activityMenuItem: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '10px',
    border: 'none',
    background: '#f8fafc',
    color: '#0f172a',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '14px',
  },
  activityMenuItemDanger: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '10px',
    border: 'none',
    background: '#fee2e2',
    color: '#b91c1c',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '14px',
  },
  activityEditInput: {
    width: '200px',
    padding: '8px 10px',
    borderRadius: '10px',
    border: '1px solid #cbd5e1',
    fontSize: '14px',
    color: '#0f172a',
    boxSizing: 'border-box',
  },
  activityText: {
    color: '#334155',
  },
  activityDone: {
    color: '#64748b',
    textDecoration: 'line-through',
  },
  activityRemove: {
    width: '30px',
    height: '30px',
    borderRadius: '8px',
    border: '1px solid #f1f5f9',
    background: '#fee2e2',
    color: '#b91c1c',
    cursor: 'pointer',
    fontWeight: '700',
    display: 'grid',
    placeItems: 'center',
  },
  activityForm: {
    display: 'grid',
    gridTemplateColumns: '1fr auto',
    gap: '10px',
    alignItems: 'center',
  },
  activityEditActions: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  },

  btnCalendar: {
    padding: '10px 20px',
    background: '#2563eb',
    color: '#ffffff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '700',
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(37,99,235,0.30)',
    transition: 'background 0.2s, box-shadow 0.2s',
    whiteSpace: 'nowrap',
  },

  daysSelector: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap',
  },
  dayChip: {
    padding: '6px 10px',
    borderRadius: '8px',
    border: '1.5px solid #cbd5e1',
    background: '#f8fafc',
    color: '#475569',
    fontSize: '12px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  dayChipActive: {
    background: '#eff6ff',
    border: '1.5px solid #2563eb',
    color: '#1d4ed8',
  },

  habitMetaExtra: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    marginBottom: '10px',
  },
  habitDiasTag: {
    fontSize: '11px',
    color: '#1d4ed8',
    background: '#eff6ff',
    borderRadius: '6px',
    padding: '3px 8px',
    display: 'inline-block',
  },
  habitMotivoTag: {
    fontSize: '11px',
    color: '#047857',
    background: '#ecfdf5',
    borderRadius: '6px',
    padding: '3px 8px',
    display: 'inline-block',
  },

  activityMeta: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap',
    marginTop: '3px',
  },
  activityDateTag: {
    fontSize: '11px',
    color: '#b45309',
    background: '#fffbeb',
    borderRadius: '5px',
    padding: '2px 7px',
    border: '1px solid #fde68a',
  },
  activityDaysTag: {
    fontSize: '11px',
    color: '#1d4ed8',
    background: '#eff6ff',
    borderRadius: '5px',
    padding: '2px 7px',
    border: '1px solid #bfdbfe',
  },

  activityFormExtended: {
  display: 'flex',
  flexWrap: 'wrap',
  gap: '8px',
  alignItems: 'center',
  },
}

export default styles
